name: commitmsg-conform
on:
  pull_request: {}
permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read
jobs:
  commitmsg-conform:
    uses: ./.github/workflows/commitmsg-conform.yml
