name: markdown-lint
on:
  pull_request: {}
permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read
jobs:
  markdown-lint:
    uses: ./.github/workflows/commitmsg-conform.yml
