name: terraform-lint-validate

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.tf"
      - "tests/**"
      - "examples/**"

  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "tests/**"
      - "examples/**"

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check Terraform Formatting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Terraform Formatting
        uses: dflook/terraform-fmt-check@v1
        with:
          path: .

  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform Configuration
    needs: fmt-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Terraform Configuration
        uses: dflook/terraform-validate@v1
        with:
          path: .
